### ISSUE TITLE
Add a setting for clean stack trace

### ISSUE THREAD

**Issue by evpl** [evpl/xteps#1]
**The problem**
The stack trace contains a lot of redundant information (like `DefaultStepWriter` methods).

**StackTrace example**
```
java.lang.RuntimeException
	at com.my.example.ExampleTest.lambda$test$0(ExampleTest.java:11)
	at com.plugatar.xteps.core.writer.DefaultStepWriter.lambda$writeRunnableStep$1(DefaultStepWriter.java:60)
	at com.plugatar.xteps.core.writer.DefaultStepWriter.writeFunctionStep(DefaultStepWriter.java:105)
	at com.plugatar.xteps.core.writer.DefaultStepWriter.writeRunnableStep(DefaultStepWriter.java:59)
	at com.plugatar.xteps.core.steps.NoCtxStepsOf.step(NoCtxStepsOf.java:86)
	at com.plugatar.xteps.Xteps.step(Xteps.java:258)
	at com.my.example.ExampleTest.test(ExampleTest.java:11)
       ...
```

**Environment**
 - Xteps version 1.0
 - Java version 1.8

**Comment by evpl** [comment]
Done
